### ISSUE TITLE
search trips by stations instead of cities

### ISSUE THREAD

**Issue by dotlambda** [juliuste/meinfernbus#5]
From my analysis of the API, I think you can search by station ID if you leave out `search_by=cities` in the query string.

The possibility to search for a trip by exact stations would be nice to have :-)

**Comment by juliuste** [comment]
Sure, I'll be working on it in the next days (:

**Comment by derhuerst** [comment]
bump.

**Comment by juliuste** [comment]
\*cough\* Sorry, I totally forgot about this. Since I'm planning to update the module to fit the [friendly-public-transport-format](ub.com/public-transport/friendly-public-transport-format) in the next few days, I'm going to work on this issue as well.

**Comment by juliuste** [comment]
Apart from today's update and stuff that might still change in the following days, you can search for stations for now by passing `{search_by: 'stations'}` in the `opt` parameter when using `journeys` 🙃

**Comment by juliuste** [comment]
And I'm really sorry that it took me an eternity to answer your question/proposal, I always forget about these GitHub issues after a few hours 😕
